[__config__]
oldver = "github.json"
newver = "github.new.json"

[nvchecker]
source = "github"
github = "lilydjwg/nvchecker"
use_max_tag = true

[serveradmin]
source = "github"
github = "innogames/serveradmin"
use_max_tag = true

[igvm]
source = "github"
github = "innogames/igvm"
use_max_tag = true

[testtool]
source = "github"
github = "innogames/testtool"
use_max_tag = true

[igmonplugins]
source = "github"
github = "innogames/igmonplugins"
use_max_tag = true

[puppet-adminapi]
source = "github"
github = "innogames/puppet-adminapi"
use_max_tag = true

[grafana]
source = "github"
github = "grafana/grafana"
use_max_tag = true

[loki]
source = "github"
github = "grafana/loki"
use_max_tag = true

[mimir]
source = "github"
github = "grafana/mimir"
use_latest_release = true

[tempo]
source = "github"
github = "grafana/tempo"
use_max_tag = true

[prometheus]
source = "github"
github = "prometheus/prometheus"
use_max_tag = true

[alertmanager]
source = "github"
github = "prometheus/alertmanager"
use_max_tag = true

[alloy]
source = "github"
github = "grafana/alloy"
use_max_tag = true

[nagioscore]
source = "github"
github = "NagiosEnterprises/nagioscore"
use_max_tag = true

[nrpe]
source = "github"
github = "NagiosEnterprises/nrpe"
use_max_tag = true

[nsca]
source = "github"
github = "NagiosEnterprises/nsca"
use_max_tag = true

[nagios-plugins]
source = "github"
github = "nagios-plugins/nagios-plugins"
use_max_tag = true

[naemon-core]
source = "github"
github = "naemon/naemon-core"
use_max_tag = true

[naemon-livestatus]
source = "github"
github = "naemon/naemon-livestatus"
use_max_tag = true

[mod_gearman]
source = "github"
github = "sni/mod_gearman"
use_max_tag = true

[mod-gearman-worker-go]
source = "github"
github = "ConSol-Monitoring/mod-gearman-worker-go"
use_max_tag = true

[Thruk]
source = "github"
github = "sni/Thruk"
use_max_tag = true

[lmd]
source = "github"
github = "sni/lmd"
use_max_tag = true

[aptly]
source = "github"
github = "aptly-dev/aptly"
use_max_tag = true

[puppet]
source = "github"
github = "puppetlabs/puppet"
use_max_tag = true

[xray-core]
source = "github"
github = "xtls/xray-core"
use_max_tag = true

[argocd]
source = "github"
github = "argoproj/argo-cd"
use_max_tag = true

[cluster-api]
source = "github"
github = "kubernetes-sigs/cluster-api"
use_max_tag = true

[cluster-api-operator]
source = "github"
github = "kubernetes-sigs/cluster-api-operator"
use_max_tag = true

[cluster-api-provider-hetzner]
source = "github"
github = "syself/cluster-api-provider-hetzner"
use_max_tag = true

[cluster-api-addon-provider-helm]
source = "github"
github = "kubernetes-sigs/cluster-api-addon-provider-helm"
use_max_tag = true

[kamaji]
source = "github"
github = "clastix/kamaji"
use_max_tag = true

[kamaji-etcd]
source = "github"
github = "clastix/kamaji-etcd"
use_max_tag = true

[cert-manager]
source = "github"
github = "cert-manager/cert-manager"
use_max_tag = true

[cloudnative-pg]
source = "github"
github = "cloudnative-pg/cloudnative-pg"
use_max_tag = true

[external-dns]
source = "github"
github = "kubernetes-sigs/external-dns"
use_max_tag = true

[harbor]
source = "github"
github = "goharbor/harbor"
use_max_tag = true

[ingress-nginx]
source = "github"
github = "kubernetes/ingress-nginx"
use_max_tag = true

[keycloak]
source = "github"
github = "keycloak/keycloak"
use_max_tag = true

[kube-prometheus-stack]
source = "github"
github = "prometheus-community/helm-charts"
use_max_tag = true
include_regex = 'kube-prometheus-stack-.*'

[kubernetes-ingress]
source = "github"
github = "haproxytech/kubernetes-ingress"
use_max_tag = true

[local-path-provisioner]
source = "github"
github = "rancher/local-path-provisioner"
use_max_tag = true

[metrics-server]
source = "github"
github = "kubernetes-sigs/metrics-server"
use_max_tag = true

[openbao]
source = "github"
github = "openbao/openbao"
use_max_tag = true

[rbac-manager]
source = "github"
github = "FairwindsOps/rbac-manager"
use_max_tag = true

[sealed-secrets]
source = "github"
github = "bitnami-labs/sealed-secrets"
use_max_tag = true

[velero]
source = "github"
github = "vmware-tanzu/velero"
use_max_tag = true

[velero-plugin-for-aws]
source = "github"
github = "vmware-tanzu/velero-plugin-for-aws"
use_max_tag = true

